### ISSUE TITLE
Bilder werden nach Update nicht mehr angezeigt

### ISSUE THREAD

**Issue by flo-assling** [FriendsOfShopware/FroshLazySizes#10]
### PHP Version

8.2

### Shopware Version

6.4.20.0 

### Actual behaviour

Nach dem Update auf v1.0.1 werden keine Bilder mehr in der Storefront angezeigt.
Bei Deaktivierung des Plugins werden wieder alle Bilder angezeigt.
Cache löschen bringt nichts, Plugin komplett neu installieren auch nicht.
Bei manuellem Hochladen der Version 1.0 werden wieder Bilder angezeigt

### Expected behaviour

Bilder sollten auch nach Plugin Update in der Storefront angezeigt werden

### Steps to Reproduce?

Update des Plugins auf v1.1

**Comment by tinect** [comment]
Thank you for contacting us.
We noticed the version was falsely built with shopware 6.5 :-( We revoked the release in store and will publish a new version soon.

**Comment by tinect** [comment]
version 1.0.2 has been released to solve the error.
