### ISSUE TITLE
is not compatible with shopware version 6.5.3.2 

### ISSUE THREAD

**Issue by getnatalia** [FriendsOfShopware/FroshLazySizes#16]
### PHP Version

8.2.3

### Shopware Version

6.5.3.2

### Actual behaviour

![LazySizes_and_LazyLoading_for_suitable_image_sizes___Shopware_Store](https://github.com/FriendsOfShopware/FroshLazySizes/assets/64019313/295af575-a85f-4f4f-a59e-920fa25b1fbb)

### Expected behaviour

Please check the compatibility with shopware version 6.5.3.2

### Steps to Reproduce?

I probably can't switch to version 6.5.3.2 in the Shopware account because this extension is not compatible.

**Comment by tinect** [comment]
Will be marked compatible soon.
