### ISSUE TITLE
FroshLazySizes is incompatible with Spno6NewsletterBusiness Plugin

### ISSUE THREAD

**Issue by JD297** [FriendsOfShopware/FroshLazySizes#18]
### Please describe the feature you would like to see implemented.

Hey, ich bin der Entwickler des Newsletter Plugins aus Shopware 6. Wir haben ein Support Ticket erhalten von einem Kunden der sowohl unser Plugin als auch euer Plugin verwendet. Dabei ist aufgefallen, dass die Bilder im Newsletter nicht mehr laden aufgrund der lazy Funktion. Gibt es eine Möglichkeit das Plugin wahlweise zu deaktivieren? Sei es durch parameter oder sonstiges.

Beste Grüße
Jan Dommasch

Hey, I'm the developer of the newsletter plugin for Shopware 6. We received a support ticket from a customer who uses both our plugin and your plugin. It was noticed that the images in the newsletter no longer load due to the lazy function. Is there a way to optionally deactivate the plugin? Be it through parameters or something else.

Best regards
Jan Dommasch

**Comment by tinect** [comment]
hi,

there is currently no way to disable it.

but I like to understand the need.

Could you please give more insights? is it a custom controller? Or is it within mails where you are using the sw-thumbnail-method of shopware?

**Comment by JD297** [comment]
Hey,
the newsletter template will be rendered via a custom controller / service. In the controller I could manipulate the context of the request. E.g. you could check in your template code if a specific extension in the context is set and then just behave like the default.

**Comment by tinect** [comment]
we could add a variable check like in #19 . could this work for you?

but is your template also used for mails? 🤔 because srcset is not supported by mail clients and therefore original images are always loaded, isn't it?

**Comment by JD297** [comment]
Yes, of course. Our newsletter plugin sends mails with that generated template. In the template also was the srcset set. The main problem seems to be that the src attribute is set with a 1x1 pixel image.

**Comment by tinect** [comment]
keep in mind you are then sending the receiver with the original image, which is in full size and not optimized. we all know the shop owners uploading their 5 MB images. this sounds like wasting traffic.

Did you recognise you can give the variable "src" into the utility? then this is used instead of the 1x1 placeholder. maybe this could also help, additionally to not send original images 🙈

But I will also finish the PR for other purposes, too.
