### ISSUE TITLE
2.1.1 - missing release tag

### ISSUE THREAD

**Issue by m-overlund** [FriendsOfShopware/FroshLazySizes#27]
### Plugin Version

2.1.1

### Actual behaviour

2.1.1 wasn't released - seem's like the job failed.

### Expected behaviour

release tag for 2.1.1

### Steps to Reproduce?

check releases

**Comment by tinect** [comment]
Thank you for the reminder. Yes, the API was broken and I released it in store by hand 🙈 
Now also released by hand on github.

Thank you.
