### ISSUE TITLE
How to use plugin function for images, inserted in templates

### ISSUE THREAD

**Issue by mariopoeschl** [FriendsOfShopware/FroshLazySizes#30]
### Question

If we use images in footer blocks, is there an option to use lazy loading and lazy sizes by adding the classes?
We tested this by adding the following code, but google page insigts doesn't recognize the images as lazy loaded:

`<img class="frosh-proc lazyautosizes lazyloaded" src="https://www.kleinmetall.de/bundles/sysgthemekm/award-logos/logo_km_50jahre…" width="80px">`

**Comment by tinect** [comment]
Hi @mariopoeschl,

while you don't have any srcset defined, there is no need for lazy sizes.
Regarding your sample, I'd recommend you just to use the HTML5-tag `loading` with value `lazy`:
`<img loading="lazy" src="https://www.kleinmetall.de/bundles/sysgthemekm/award-logos/logo_km_50jahre…" width="80px">`
Refs: https://web.dev/articles/browser-level-image-lazy-loading?hl=de

But, if you want to use the lazy-sizes plugin to do this:
Use class `lazyload` and set `src` as `data-src`.
Refs: https://github.com/aFarkas/lazysizes?tab=readme-ov-file#lazysizes:~:text=lazysizes%20does%20not%20need%20any%20JS%20configuration

**Comment by tinect** [comment]
I'll close here due to inactivity.
