### ISSUE TITLE
Images "above the fold" on category pages are lazy loaded

### ISSUE THREAD

**Issue by gamerlion7** [FriendsOfShopware/FroshLazySizes#33]
### Actual behaviour

Images "above the fold" on category pages are lazy loaded.

### Expected behaviour

Images "above the fold" should not be lazy loaded, because it increases the page load time and Lighthouse complains.

My suggestion if there is no easy solution:
- Do not lazy load the first 4 images if the window is so small that 1 product is shown per row.
- Do not lazy load the first 4 images if the window is so small that 2 products are shown per row.
- Do not lazy load the first 6 images if the window is so small that 3 products are shown per row.
- Do not lazy load the first 8 images if the window is so small that 4 products are shown per row.

If that is still too complicated:
Do not lazy load the first 4 images.

### Steps to Reproduce?

Load and inspect a category page.

**Comment by tinect** [comment]
as mentioned in mail, this will not happen due to possible bad performance.
please use the classes mentioned in readme.
