### ISSUE TITLE
Images in product categories are not shown correctly 

### ISSUE THREAD

**Issue by SimonBKohlschein** [FriendsOfShopware/FroshLazySizes#6]
### PHP Version

8.1

### Shopware Version

6.4.18.0

### Actual behaviour

Images in product categories are not shown correctly. Instead of the src of the img being an URL it is a string like this `"data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="`, causing the image not to be rendered.

Example:

`html
<img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="https://ourcdn/media/d1/99/8d/1664181798/wabenplatten-beelite-kohlschein-oberflaechen-kantenansicht.jpg?width=3000" data-srcset="https://ourcdn/media/d1/99/8d/1664181798/wabenplatten-beelite-kohlschein-oberflaechen-kantenansicht.jpg?width=3000 1201w, https://ourcdn/media/d1/99/8d/1664181798/wabenplatten-beelite-kohlschein-oberflaechen-kantenansicht.jpg?width=1200 1200w, https://ourcdn/media/d1/99/8d/1664181798/wabenplatten-beelite-kohlschein-oberflaechen-kantenansicht.jpg?width=1100 1100w, https://ourcdn/media/d1/99/8d/1664181798/wabenplatten-beelite-kohlschein-oberflaechen-kantenansicht.jpg?width=1000 1000w, https://ourcdn/media/d1/99/8d/1664181798/wabenplatten-beelite-kohlschein-oberflaechen-kantenansicht.jpg?width=900 900w, https://ourcdn/media/d1/99/8d/1664181798/wabenplatten-beelite-kohlschein-oberflaechen-kantenansicht.jpg?width=800 800w, https://ourcdn/media/d1/99/8d/1664181798/wabenplatten-beelite-kohlschein-oberflaechen-kantenansicht.jpg?width=700 700w, https://ourcdn/media/d1/99/8d/1664181798/wabenplatten-beelite-kohlschein-oberflaechen-kantenansicht.jpg?width=600 600w, https://ourcdn/media/d1/99/8d/1664181798/wabenplatten-beelite-kohlschein-oberflaechen-kantenansicht.jpg?width=500 500w, https://ourcdn/media/d1/99/8d/1664181798/wabenplatten-beelite-kohlschein-oberflaechen-kantenansicht.jpg?width=400 400w, https://ourcdn/media/d1/99/8d/1664181798/wabenplatten-beelite-kohlschein-oberflaechen-kantenansicht.jpg?width=300 300w" data-sizes="auto" data-aspectratio="1200/1200" data-parent-fit="contain" class="frosh-proc lazyload product-image is-standard" alt="BEElite print Wabenplatten weiß / braun" title="BEElite print Wabenplatten weiß / braun" style="aspect-ratio:1200/1200;">
`

### Expected behaviour

The image should be displayed.

### Steps to Reproduce?

This happens to all images on product category pages. We are using this plugin in combination with [BunnyCdn Media Storage Plugin v2 ](https://store.shopware.com/frosh48851065217f/bunnycdn-media-storage-plugin-v2.html) and [ThumbnailProcessor incl. Webp-Support](https://store.shopware.com/en/frosh69611263569f/thumbnailprocessor-incl.-webp-support.html).

**Comment by tinect** [comment]
Could you please check for javascript errors within your devtool?

**Comment by SimonBKohlschein** [comment]
Thank you. There was a JavaScript error due to another plugin which caused this.
