### ISSUE TITLE
Nach der Installation sind die Bilder weg

### ISSUE THREAD

**Issue by Openliquid** [FriendsOfShopware/FroshLazySizes#7]
### PHP Version

8.1.17

### Shopware Version

6.4.19

### Actual behaviour

Hallo Friends of Shopware,

vielen Dank für die Bereitstellung des Lazy Loading Plugins. Nach der Installation sind erstmal alle Bilder weg, siehe 
Screenshot.
Müssen die neu generiert werden? Kann man das manuell irgendwie anstoßen?

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/128682030/227137514-2854ce72-9192-40b5-84a1-d630f0496207.png">

Vielen Dank.

Schöne Grüße,
Matthias Rau

### Expected behaviour

.

### Steps to Reproduce?

.

**Comment by tinect** [comment]
Hi @Openliquid 

there is no need to generate anything.

Could you verify there is no Javascript error in Console of DevTools, which might prevent the plugin from working?

Alternative, how did you install the plugin? ZIP (which one?), composer, store, ...?

**Comment by tinect** [comment]
Hi @Openliquid,
I'll close this issue due to inactivity.

You are welcome to come back if the issue persists on your side.
